# Generated by Django 4.0.5 on 2024-02-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order', 'name', 'price', 'quantity', 'image')},
        ),
    ]
